In [29]:
import torch
torch.__version__

'2.8.0+cpu'

In [30]:
scalar = torch.tensor(7)
scalar #tensor(7)
scalar.item()  # get the value as a standard Python number
scalar.ndim  # number of dimensions

0

In [31]:
vector = torch.tensor([7, 7])
vector
vector.ndim
vector.shape

torch.Size([2])

In [32]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX
MATRIX.ndim
MATRIX.shape


torch.Size([2, 2])

In [33]:
TENSOR = torch.tensor([[[1, 2, 3],[3,6,9],[2,4,5]]])
TENSOR
TENSOR.ndim
TENSOR.shape

torch.Size([1, 3, 3])

In [34]:
random_tensor = torch.rand(size=(3, 4))
random_tensor , random_tensor.dtype

(tensor([[0.4563, 0.9719, 0.3968, 0.1496],
         [0.4743, 0.9973, 0.4436, 0.9726],
         [0.5194, 0.5337, 0.7050, 0.3362]]),
 torch.float32)

In [35]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor, random_image_size_tensor.ndim , random_image_size_tensor.dtype

(tensor([[[0.7891, 0.1694, 0.1800],
          [0.7177, 0.6988, 0.5510],
          [0.2485, 0.8518, 0.0963],
          ...,
          [0.6048, 0.1507, 0.9345],
          [0.9424, 0.8554, 0.6705],
          [0.8658, 0.9826, 0.4201]],
 
         [[0.7863, 0.7398, 0.6700],
          [0.6444, 0.1292, 0.1217],
          [0.5528, 0.4964, 0.9242],
          ...,
          [0.2026, 0.9024, 0.3382],
          [0.4570, 0.0918, 0.4522],
          [0.9551, 0.4328, 0.0825]],
 
         [[0.1491, 0.6914, 0.5865],
          [0.3077, 0.3311, 0.0851],
          [0.3749, 0.9226, 0.7304],
          ...,
          [0.8573, 0.8127, 0.0742],
          [0.0503, 0.9606, 0.2824],
          [0.7685, 0.9292, 0.1753]],
 
         ...,
 
         [[0.5480, 0.7382, 0.3771],
          [0.3222, 0.3321, 0.5223],
          [0.6624, 0.7138, 0.6040],
          ...,
          [0.4589, 0.1804, 0.4239],
          [0.8231, 0.8119, 0.3439],
          [0.5454, 0.6698, 0.8395]],
 
         [[0.1614, 0.5587, 0.3654],
          [0

In [36]:
zeroes = torch.zeros(size=(3, 4))
zeroes, zeroes.ndim, zeroes.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 2,
 torch.float32)

In [37]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype , ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 2)

In [38]:
zero_to_ten_error = torch.range(0,10)

zero_to_ten = torch.arange(0, 10,1)
zero_to_ten

/tmp/ipykernel_49072/1400445458.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_error = torch.range(0,10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
ten_zeroes = torch.zeros_like(input=zero_to_ten )
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], 
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.ndim , float_32_tensor.device

(torch.Size([3]), torch.float32, 1, device(type='cpu'))

In [41]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [42]:
some_tensor = torch.rand(3, 4)

print(some_tensor)

print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.2313, 0.2927, 0.3386, 0.3708],
        [0.0831, 0.0944, 0.6568, 0.7708],
        [0.1053, 0.1467, 0.1932, 0.9118]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [43]:
tensor = torch.tensor([1,2,3])
tensor + 10
tensor * 100000000000000000
tensor
tensor -100


tensor([-99, -98, -97])

In [44]:
print(tensor,"*",tensor)
print(tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [45]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [46]:
tensor*tensor
torch.matmul(tensor, tensor)  # matrix multiplication

tensor(14)

In [47]:
tensor@tensor

tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 341 μs, sys: 0 ns, total: 341 μs
Wall time: 212 μs


tensor(14)

In [49]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) # (this will error)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [50]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [51]:
torch.mm(tensor_A, tensor_B.T)  # torch.mm = matrix multiplication)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [54]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
x= tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [ ]:
x=torch.arange(0,100,10)
x
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


(tensor(90), tensor(0), tensor(45.), tensor(450))

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [ ]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped.shape, x_reshaped

(torch.Size([1, 7]), tensor([[1., 2., 3., 4., 5., 6., 7.]]))

In [ ]:
z=x.view(1,7) #Same view only!
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z[:,0] = 5
z,x,x.shape

(tensor([[5., 2., 3., 4., 5., 6., 7.]]),
 tensor([5., 2., 3., 4., 5., 6., 7.]),
 torch.Size([7]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.]]),
 torch.Size([7, 4]))

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [ ]:
x_original = torch.rand(size=(224,224,3))

x_permuter = x_original.permute(2,0,1) # Changes the axis order 

print(f"Original shape: {x_original.shape}\nNew shape: {x_permuter.shape}")

Original shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
#Pytorch and NumPy
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array + 1
array, tensor

(array([ 4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor=torch.ones(7)
numpy_tensor = tensor.numpy().astype(np.float64)
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1., 1., 1.]))

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]), array([1., 1., 1., 1., 1., 1., 1.]))

In [ ]:
import torch

r_t_A=torch.rand(3,4)
r_t_B=torch.rand(3,4)

r_t_A, r_t_B,r_t_A==r_t_B



(tensor([[0.8973, 0.3629, 0.1748, 0.2401],
         [0.5457, 0.7303, 0.5268, 0.6694],
         [0.3213, 0.4008, 0.2892, 0.9977]]),
 tensor([[0.6649, 0.5646, 0.9323, 0.4621],
         [0.4027, 0.1680, 0.1170, 0.5063],
         [0.6061, 0.5141, 0.1907, 0.0445]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [55]:
import torch
import random

R_SEED=42
torch.manual_seed(seed=R_SEED)
random_tensor
random.seed(R_SEED)


In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device
# Count number of devices
torch.cuda.device_count()

0

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [ ]:
tensor_on_gpu.numpy()
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

tensor_on_gpu

tensor([1, 2, 3])