In [3]:
import torch
torch.__version__

'2.8.0+cpu'

In [6]:
scalar = torch.tensor(7)
scalar #tensor(7)
scalar.item()  # get the value as a standard Python number
scalar.ndim  # number of dimensions

0

In [11]:
vector = torch.tensor([7, 7])
vector
vector.ndim
vector.shape

torch.Size([2])

In [13]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX
MATRIX.ndim
MATRIX.shape


torch.Size([2, 2])

In [14]:
TENSOR = torch.tensor([[[1, 2, 3],[3,6,9],[2,4,5]]])
TENSOR
TENSOR.ndim
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
random_tensor = torch.rand(size=(3, 4))
random_tensor , random_tensor.dtype

(tensor([[0.9419, 0.0329, 0.1477, 0.5212],
         [0.1295, 0.7043, 0.0444, 0.9245],
         [0.9763, 0.9775, 0.5790, 0.0414]]),
 torch.float32)

In [18]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor, random_image_size_tensor.ndim , random_image_size_tensor.dtype

(tensor([[[0.4281, 0.5122, 0.6818],
          [0.6864, 0.6126, 0.9871],
          [0.9530, 0.3129, 0.6402],
          ...,
          [0.7328, 0.6350, 0.3570],
          [0.4193, 0.9627, 0.6935],
          [0.7267, 0.9112, 0.2421]],
 
         [[0.0285, 0.4959, 0.6729],
          [0.9430, 0.5625, 0.6883],
          [0.8451, 0.7264, 0.5212],
          ...,
          [0.8736, 0.5322, 0.1667],
          [0.6863, 0.8426, 0.9987],
          [0.8793, 0.2717, 0.5782]],
 
         [[0.3960, 0.1882, 0.2127],
          [0.8635, 0.8619, 0.4822],
          [0.3341, 0.5941, 0.5287],
          ...,
          [0.8217, 0.8998, 0.2808],
          [0.4490, 0.0727, 0.9813],
          [0.5607, 0.8074, 0.1374]],
 
         ...,
 
         [[0.0246, 0.7662, 0.2127],
          [0.4401, 0.0234, 0.8329],
          [0.4698, 0.2012, 0.4085],
          ...,
          [0.9855, 0.0220, 0.2872],
          [0.1180, 0.8902, 0.5153],
          [0.2850, 0.4645, 0.0919]],
 
         [[0.0218, 0.8354, 0.7414],
          [0

In [19]:
zeroes = torch.zeros(size=(3, 4))
zeroes, zeroes.ndim, zeroes.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 2,
 torch.float32)

In [21]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype , ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 2)

In [22]:
zero_to_ten_error = torch.range(0,10)

zero_to_ten = torch.arange(0, 10,1)
zero_to_ten

/tmp/ipykernel_37516/1400445458.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_error = torch.range(0,10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
ten_zeroes = torch.zeros_like(input=zero_to_ten )
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], 
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.ndim , float_32_tensor.device

(torch.Size([3]), torch.float32, 1, device(type='cpu'))

In [30]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [32]:
some_tensor = torch.rand(3, 4)

print(some_tensor)

print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.1740, 0.9602, 0.8409, 0.3791],
        [0.6733, 0.2567, 0.8758, 0.9391],
        [0.1460, 0.3981, 0.9857, 0.8893]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [35]:
tensor = torch.tensor([1,2,3])
tensor + 10
tensor * 10

tensor([10, 20, 30])