In [3]:
import torch
torch.__version__

'2.8.0+cpu'

In [4]:
scalar = torch.tensor(7)
scalar #tensor(7)
scalar.item()  # get the value as a standard Python number
scalar.ndim  # number of dimensions

0

In [5]:
vector = torch.tensor([7, 7])
vector
vector.ndim
vector.shape

torch.Size([2])

In [6]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX
MATRIX.ndim
MATRIX.shape


torch.Size([2, 2])

In [7]:
TENSOR = torch.tensor([[[1, 2, 3],[3,6,9],[2,4,5]]])
TENSOR
TENSOR.ndim
TENSOR.shape

torch.Size([1, 3, 3])

In [8]:
random_tensor = torch.rand(size=(3, 4))
random_tensor , random_tensor.dtype

(tensor([[0.2253, 0.8592, 0.7158, 0.8085],
         [0.3950, 0.7144, 0.0985, 0.2068],
         [0.7588, 0.1207, 0.3737, 0.3446]]),
 torch.float32)

In [9]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor, random_image_size_tensor.ndim , random_image_size_tensor.dtype

(tensor([[[0.2467, 0.3767, 0.7324],
          [0.3598, 0.5349, 0.3789],
          [0.1927, 0.0242, 0.6394],
          ...,
          [0.4573, 0.2229, 0.5012],
          [0.8696, 0.7242, 0.1333],
          [0.9515, 0.5238, 0.9609]],
 
         [[0.4254, 0.4906, 0.9427],
          [0.6141, 0.2563, 0.8421],
          [0.3615, 0.8591, 0.4944],
          ...,
          [0.6667, 0.9026, 0.7514],
          [0.6828, 0.3184, 0.3635],
          [0.5697, 0.0824, 0.6829]],
 
         [[0.0489, 0.2022, 0.4796],
          [0.9277, 0.5088, 0.1388],
          [0.6836, 0.3579, 0.2568],
          ...,
          [0.3352, 0.5074, 0.9316],
          [0.1531, 0.9073, 0.6883],
          [0.1757, 0.4990, 0.6802]],
 
         ...,
 
         [[0.1233, 0.2316, 0.0877],
          [0.2243, 0.3458, 0.0863],
          [0.1170, 0.5487, 0.4679],
          ...,
          [0.1839, 0.9936, 0.6103],
          [0.2706, 0.0482, 0.4806],
          [0.1117, 0.2134, 0.8460]],
 
         [[0.8727, 0.4417, 0.8411],
          [0

In [10]:
zeroes = torch.zeros(size=(3, 4))
zeroes, zeroes.ndim, zeroes.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 2,
 torch.float32)

In [11]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype , ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 2)

In [12]:
zero_to_ten_error = torch.range(0,10)

zero_to_ten = torch.arange(0, 10,1)
zero_to_ten

/tmp/ipykernel_10232/1400445458.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_error = torch.range(0,10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
ten_zeroes = torch.zeros_like(input=zero_to_ten )
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
import torch
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], 
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.ndim , float_32_tensor.device

(torch.Size([3]), torch.float32, 1, device(type='cpu'))

In [15]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float64) # torch.half would also work

float_16_tensor.dtype

torch.float64

In [16]:
import random

some_tensor = torch.rand(3, 4)

print(some_tensor)

print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.7903, 0.2735, 0.6450, 0.8723],
        [0.8606, 0.5508, 0.2851, 0.3041],
        [0.3347, 0.4454, 0.0209, 0.2420]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [17]:
tensor = torch.tensor([1,2,3])
tensor + 10
tensor * 100000000000000000
tensor
tensor -100


tensor([-99, -98, -97])

In [18]:
print(tensor,"*",tensor)
print(tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [19]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [20]:
tensor*tensor
torch.matmul(tensor, tensor)  # matrix multiplication

tensor(14)

In [21]:
tensor@tensor

tensor(14)

In [22]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 864 μs, sys: 0 ns, total: 864 μs
Wall time: 1.69 ms


tensor(14)

In [23]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) # (this will error)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [24]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [25]:
torch.mm(tensor_A, tensor_B.T)  # torch.mm = matrix multiplication

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [26]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
x= tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [27]:
x=torch.arange(0,100,10)
x
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


(tensor(90), tensor(0), tensor(45.), tensor(450))

In [28]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [29]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [30]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [31]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped.shape, x_reshaped

(torch.Size([1, 7]), tensor([[1., 2., 3., 4., 5., 6., 7.]]))

In [32]:
z=x.view(1,7) #Same view only!
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [33]:
z[:,0] = 5
z,x,x.shape

(tensor([[5., 2., 3., 4., 5., 6., 7.]]),
 tensor([5., 2., 3., 4., 5., 6., 7.]),
 torch.Size([7]))

In [34]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.]]),
 torch.Size([7, 4]))

In [35]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\n New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\n New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

 New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])

 New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [36]:
x_original = torch.rand(size=(224,224,3))
x_permuter = x_original.permute(2,0,1) # Changes the axis order

print(f"Original shape: {x_original.shape}\nNew shape: {x_permuter.shape}")

Original shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [37]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [38]:
x[:,0]

tensor([[1, 2, 3]])

In [39]:
x[:,:,1]

tensor([[2, 5, 8]])

In [40]:
x[:,1,1]

tensor([5])

In [41]:
x[0,0,:]

tensor([1, 2, 3])

In [42]:
#Pytorch and NumPy
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [43]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor=torch.ones(7)
numpy_tensor = tensor.numpy().astype(np.float64)


tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1., 1., 1.]))

In [45]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]), array([1., 1., 1., 1., 1., 1., 1.]))

In [46]:
import torch

r_t_A=torch.rand(3,4)
r_t_B=torch.rand(3,4)

r_t_A, r_t_B,r_t_A==r_t_B



(tensor([[0.8016, 0.3649, 0.6286, 0.9663],
         [0.7687, 0.4566, 0.5745, 0.9200],
         [0.3230, 0.8613, 0.0919, 0.3102]]),
 tensor([[0.9536, 0.6002, 0.0351, 0.6826],
         [0.3743, 0.5220, 0.1336, 0.9666],
         [0.9754, 0.8474, 0.8988, 0.1105]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [47]:
import torch
import random

R_SEED=42
torch.manual_seed(seed=R_SEED)
random_tensor
random.seed(R_SEED)


In [48]:
# Check for GPU
import torch
torch.cuda.is_available()

# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device
# Count number of devices
torch.cuda.device_count()

0

In [49]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [50]:
tensor_on_gpu.numpy()
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

tensor_on_gpu

tensor([1, 2, 3])